# 使用 Node.js 官方镜像作为基础镜像
FROM node:20-alpine3.19 AS build

# # 设置镜像源，安装依赖软件、设置时区，并安装应用依赖 (测试)
# RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories && \
#     apk --update --no-cache add git tzdata libc6-compat && \
#     cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
#     echo "Asia/Shanghai" > /etc/timezone && \
#     npm config set registry https://registry.npmmirror.com -g && \
#     git clone -b my-branch https://github.com/zscmmm/NotionNext.git /app/NotionNext && \
#     cd /app/NotionNext && rm -rf .git && yarn install --frozen-lockfile && \
#     yarn build
WORKDIR /app/NotionNext
COPY . .
RUN apk add --no-cache libc6-compat && yarn install --frozen-lockfile && yarn build 

# 移除缓存
RUN yarn install --production \
    && yarn cache clean && rm -rf .git 

# 使用更小的镜像来运行应用程序
FROM node:20-alpine3.19 

# 设置工作目录
WORKDIR /app/NotionNext

# 从构建阶段复制已编译的文件
COPY --from=build /app/NotionNext /app/NotionNext
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
# 设置容器的启动命令
CMD ["yarn", "start"]

# 暴露应用程序运行的端口
EXPOSE 3000